name: Build and Publish Monorepo

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install Dependencies
        run: |
          pnpm install

      # This step specifically builds the SvelteKit project and regenerates .svelte-kit
      # - name: Build SvelteKit Project
      #   working-directory: libs/sveltekit
      #   run: |
      #     pnpm run build

      # Debugging step to check if .svelte-kit was created
      - name: Check .svelte-kit folder
        working-directory: libs/sveltekit
        run: |
          ls -la .svelte-kit || echo ".svelte-kit folder not found!"

      # Build all packages (React, SvelteKit, Vue)
      - name: Build All Packages
        run: |
          pnpm -r run build

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Set up NPM auth token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # Publish the Monorepo (root package)
      - name: Publish Monorepo Root Package
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publish React Package
      - name: Publish React Package
        run: |
          cd libs/react
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publish SvelteKit Package (after .svelte-kit has been generated in the build step)
      - name: Publish SvelteKit Package
        run: |
          cd libs/sveltekit
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publish Vue Package
      - name: Publish Vue Package
        run: |
          cd libs/vue
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
